// mock.js - Semillas

// ========== DEPARTAMENTO DE PROTECCIÓN Y USO DE VARIEDADES (DPUV) ==========

export const procedimientos_departamento_proteccion = [
    { title: "PRO-DPUV-100 Procedimiento RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/Resolucion-SENAVE-N-506-2025-PRO-DPUV-100-RNCP.pdf" },
    { title: "PRO-DPUV-003 Registro Nacional de Cultivares Comerciales (RNCC)", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/PRO-DPUV-003 Registro Nacional de Cultivares Comerciales (RNCC).pdf" },
    { title: "PRO-DPUV-102 Procedimiento para el Registro de Evaluadores de Variedades", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/PRO-DPUV-102%20Procedimiento%20para%20el%20Registro%20de%20Evaluadores%20de%20Variedades.docx" },
    { title: "PRO-DPUV-103 Procedimiento para la Habilitación de Ensayos por Especie", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/PRO-DPUV-103%20Procedimiento%20para%20la%20Habilitaci%C3%B3n%20de%20Ensayos%20por%20Especie.docx" }
];

export const formularios_departamento_proteccion = [
    { title: "FOR-DPUV-028 DESCRIPCION DE SOJA EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-028 DESCRIPCION DE SOJA EN EL RNCP.docx" },
    { title: "FOR-DPUV-029 DESCRIPCION DE SOJA EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-029 DESCRIPCION DE SOJA EN EL RNCC.docx" },
    { title: "FOR-DPUV-030 DESCRIPCION DE TRIGO EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-030 DESCRIPCION DE TRIGO EN EL RNCP.docx" },
    { title: "FOR-DPUV-031 DESCRIPCION DE TRIGO EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-031 DESCRIPCION DE TRIGO EN EL RNCC.docx" },
    { title: "FOR-DPUV-032 DESCRIPCION DE MAIZ EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-032 DESCRIPCION DE MAIZ EN EL RNCC.docx" },
    { title: "FOR-DPUV-033 DESCRIPCION DE ARROZ EN El RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-033 DESCRIPCION DE ARROZ EN El RNCP.docx" },
    { title: "FOR-DPUV-034 DESCRIPCION DE ARROZ EN El RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-034 DESCRIPCION DE ARROZ EN El RNCC.docx" },
    { title: "FOR-DPUV-035 DESCRIPTOR DE CANOLA EN EL RNC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-035 DESCRIPTOR DE CANOLA EN EL RNCC.doc" },
    { title: "FOR-DPUV-036 DESCRIPCION DE UROCHLOA SPP EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-036 DESCRIPCION DE UROCHLOA SPP EN EL RNCC.docx" },
    { title: "FOR-DPUV-037 DESCRIPCION DE MIJO EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-037 DESCRIPCION DE MIJO EN EL RNCP.docx" },
    { title: "FOR-DPUV-038 DESCRIPCION DE MIJO EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-038 DESCRIPCION DE MIJO EN EL RNCC.docx" },
    { title: "FOR-DPUV-039 DESCRIPCION DE KAKI EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-039 DESCRIPCION DE KAKI EN EL RNCC.docx" },
    { title: "FOR-DPUV-040 DESCRIPCION DE SORGO EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-040 DESCRIPCION DE SORGO EN EL RNCC.docx" },
    { title: "FOR-DPUV-041 DESCRIPTOR DE ACEVEN EN EL RNC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-041 DESCRIPTOR DE ACEVEN EN EL RNCC.doc" },
    { title: "FOR-DPUV-042 DESCRIPCION DE JATROPHA EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-042 DESCRIPCION DE JATROPHA EN EL RNCP.docx" },
    { title: "FOR-DPUV-043 DESCRIPCION DE AVENA EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-043 DESCRIPCION DE AVENA EN EL RNCP.docx" },
    { title: "FOR-DPUV-044 DESCRIPCION DE AVENA EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-044 DESCRIPCION DE AVENA EN EL RNCC.docx" },
    { title: "FOR-DPUV-045 DESCRIPCION DE UROCHLOA SPP EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-045 DESCRIPCION DE UROCHLOA SPP EN EL RNCP.docx" },
    { title: "FOR-DPUV-046 DESCRIPCION DE MEGATHYRSUS SPP EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-046 DESCRIPCION DE MEGATHYRSUS SPP EN EL RNCP.docx" },
    { title: "FOR-DPUV-047 DESCRIPCION DE MEGATHYRSUS SPP EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-047 DESCRIPCION DE MEGATHYRSUS SPP EN EL RNCC.docx" },
    { title: "FOR-DPUV-048 DESCRIPCION DE ZARZAMORA EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-048 DESCRIPCION DE ZARZAMORA EN EL RNCP.docx" },
    { title: "FOR-DPUV-049 DESCRIPCION DE JATROPHA EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-049 DESCRIPCION DE JATROPHA EN EL RNCC.docx" },
    { title: "FOR-DPUV-050 DESCRIPCION DE AGUACATE Porta Injerto EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-050 DESCRIPCION DE AGUACATE Porta Injerto EN EL RNCC.docx" },
    { title: "FOR-DPUV-051 DESCRIPCION DE EUCALIPTO EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-051 DESCRIPCION DE EUCALIPTO EN EL RNCP.docx" },
    { title: "FOR-DPUV-052 DESCRIPCION DE EUCALIPTO EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-052 DESCRIPCION DE EUCALIPTO EN EL RNCC.docx" },
    { title: "FOR-DPUV-053 DESCRIPCION DE CEDRO AUSTRALIANO EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-053 DESCRIPCION DE CEDRO AUSTRALIANO EN EL RNCC.docx" },
    { title: "FOR-DPUV-054 DESCRIPCION DE FRUTILLA EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-054 DESCRIPCION DE FRUTILLA EN EL RNCC.docx" },
    { title: "FOR-DPUV-055 DESCRIPCION DE POROTO EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-055 DESCRIPCION DE POROTO EN EL RNCC.docx" },
    { title: "FOR-DPUV-056 DESCRIPCION DE POROTO EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-056 DESCRIPCION DE POROTO EN EL RNCP.docx" },
    { title: "FOR-DPUV-057 DESCRIPCION DE CANA DE AZUCAR EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-057 DESCRIPCION DE CANA DE AZUCAR EN EL RNCC.docx" },
    { title: "FOR-DPUV-058 DESCRIPCION DE PAPA EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-058 DESCRIPCION DE PAPA EN EL RNCC.docx" },
    { title: "FOR-DPUV-059 DESCRIPCION DE MANDIOCA EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-059 DESCRIPCION DE MANDIOCA EN EL RNCC.docx" },
    { title: "FOR-DPUV-060 DESCRIPCION DE ALGODON EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-060 DESCRIPCION DE ALGODON EN EL RNCC.docx" },
    { title: "FOR-DPUV-061 DESCRIPCION DE ZARZAMORA EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-061 DESCRIPCION DE ZARZAMORA EN EL RNCC.docx" },
    { title: "FOR-DPUV-062 DESCRIPCION DE MANI EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-062 DESCRIPCION DE MANI EN EL RNCC.docx" },
    { title: "FOR-DPUV-063 DESCRIPCION DE CÁÑAMO EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-063 DESCRIPCION DE CANAMO EN EL RNCP.docx" },
    { title: "FOR-DPUV-064 DESCRIPCION DE POMELO EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-064 DESCRIPCION DE POMELO EN EL RNCC.docx" },
    { title: "FOR-DPUV-065 DESCRIPTOR DE PHOENIX DACTYLIFERA EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-065 DESCRIPTOR DE PHOENIX DACTYLIFERA EN EL RNCC.docx" },
    { title: "FOR-DPUV-066 DESCRIPCION DE CANA DE AZUCAR EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-066 DESCRIPCION DE CANA DE AZUCAR EN EL RNCP.docx" },
    { title: "FOR-DPUV-067 DESCRIPCION DE CÁÑAMO EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-067 DESCRIPCION DE CANAMO EN EL RNCC.docx" },
    { title: "FOR-DPUV-068 DESCRIPCION DE MANI EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-068 DESCRIPCION DE MANI EN EL RNCP.docx" },
    { title: "FOR-DPUV-069 DESCRIPCION DE CANOLA EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-069 DESCRIPCION DE CANOLA EN EL RNCP.docx" },
    { title: "FOR-DPUV-070 DESCRIPCION DE KAA HEE EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-070 DESCRIPCION DE KAA HEE EN EL RNCP.docx" },
    { title: "FOR-DPUV-071 DESCRIPCION DE KAA HEE EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-071 DESCRIPCION DE KAA HEE EN EL RNCC.docx" },
    { title: "FOR-DPUV-072 DESCRIPCION DE CANNABIS SP EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-072 DESCRIPCION DE CANNABIS SP EN EL RNCC.docx" },
    { title: "FOR-DPUV-073 DESCRIPCION DE CANNABIS SP EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-073 DESCRIPCION DE CANNABIS SP EN EL RNCP.docx" },
    { title: "FOR-DPUV-074 DESCRIPCION DE PAULOWNIA SP EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-074 DESCRIPCION DE PAULOWNIA SP EN EL RNCC.docx" },
    { title: "FOR-DPUV-075 DESCRIPCION DE PAULOWNIA SP EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-075 DESCRIPCION DE PAULOWNIA SP EN EL RNCP.docx" },
    { title: "FOR-DPUV-076 DESCRIPCION DE MACADAMIA SP EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-076 DESCRIPCION DE MACADAMIA SP EN EL RNCC.docx" },
    { title: "FOR-DPUV-077 DESCRIPCION DE MACADAMIA SP EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-077 DESCRIPCION DE MACADAMIA SP EN EL RNCP.docx" },
    { title: "FOR-DPUV-078 DESCRIPCION DE FRAMBUESO EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-078 DESCRIPCION DE FRAMBUESO EN EL RNCP.docx" },
    { title: "FOR-DPUV-079 DESCRIPCION DE FRAMBUESO EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-079 DESCRIPCION DE FRAMBUESO EN EL RNCC.docx" },
    { title: "FOR-DPUV-080 DESCRIPCION DE SESAMO EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-080 DESCRIPCION DE SESAMO EN EL RNCC.docx" },
    { title: "FOR-DPUV-081 DESCRIPCION DE SESAMO EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-081 DESCRIPCION DE SESAMO EN EL RNCP.docx" },
    { title: "FOR-DPUV-082 DESCRIPCION DE OPUNTIA EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-082 DESCRIPCION DE OPUNTIA EN EL RNCP.docx" },
    { title: "FOR-DPUV-083 DESCRIPCION DE FRUTILLA EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-083 DESCRIPCION DE FRUTILLA EN EL RNCP.docx" },
    { title: "FOR-DPUV-084 DESCRIPCION DE OPUNTIA EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-084 DESCRIPCION DE OPUNTIA EN EL RNCC.docx" },
    { title: "FOR-DPUV-085 DESCRIPCION DE BANANA EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-085 DESCRIPCION DE BANANA EN EL RNCP.docx" },
    { title: "FOR-DPUV-086 DESCRIPCION DE BANANA EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-086 DESCRIPCION DE BANANA EN EL RNCC.docx" },
    { title: "FOR-DPUV-087 DESCRIPCION DE GIRASOL EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-087 DESCRIPCION DE GIRASOL EN EL RNCP.docx" },
    { title: "FOR-DPUV-088 DESCRIPCION DE GIRASOL EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-088 DESCRIPCION DE GIRASOL EN EL RNCC.docx" },
    { title: "FOR-DPUV-089 DESCRIPCION DE TÁRTAGO EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-089 DESCRIPCION DE TARTAGO EN EL RNCP.docx" },
    { title: "FOR-DPUV-090 DESCRIPCION DE TÁRTAGO EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-090 DESCRIPCION DE TARTAGO EN EL RNCC.docx" },
    { title: "FOR-DPUV-091 DESCRIPCION DE ALGODON EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-091 DESCRIPCION DE ALGODON EN EL RNCP.docx" },
    { title: "FOR-DPUV-092 DESCRIPCION DE SETARIA SPHACELATA EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-092 DESCRIPCION DE SETARIA SPHACELATA EN EL RNCP.docx" },
    { title: "FOR-DPUV-093 DESCRIPCION DE CULTIVARES DE TABACO EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-093 DESCRIPCION DE CULTIVARES DE TABACO EN EL RNCP.docx" },
    { title: "FOR-DPUV-094 DESCRIPCION DE CEBOLLA EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-094 DESCRIPCION DE CEBOLLA EN EL RNCP.docx" },
    { title: "FOR-DPUV-095 DESCRIPCION DE CEBOLLA EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-095 DESCRIPCION DE CEBOLLA EN EL RNCC.docx" },
    { title: "FOR-DPUV-096 DESCRIPCION DE CULTIVARES DE TABACO EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-096 DESCRIPCION DE CULTIVARES DE TABACO EN EL RNCC.docx" },
    { title: "FOR-DPUV-097 DESCRIPCION DE CHIA EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-097 DESCRIPCION DE CHIA EN EL RNCC.docx" },
    { title: "FOR-DPUV-098 DESCRIPCION DE CHIA EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-098 DESCRIPCION DE CHIA EN EL RNCP.docx" },
    { title: "FOR-DPUV-099 DESCRIPCION DE NARANJA EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-099 DESCRIPCION DE NARANJA EN EL RNCC.docx" },
    { title: "FOR-DPUV-100 DESCRIPTOR DE BRASSICA CARINATA EN EL RNC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-100 DESCRIPTOR DE BRASSICA CARINATA EN EL RNCC.doc" },
    { title: "FOR-DPUV-101 DESCRIPCION DE CULTIVARES DE TOMATE EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-101 DESCRIPCION DE CULTIVARES DE TOMATE EN EL RNCC.docx" },
    { title: "FOR-DPUV-102 DESCRIPCION DE LOCOTE EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-102 DESCRIPCION DE LOCOTE EN EL RNCC.docx" },
    { title: "FOR-DPUV-103 DESCRIPCION DE MELON EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-103 DESCRIPCION DE MELON EN EL RNCC.docx" },
    { title: "FOR-DPUV-104 DESCRIPCION DE BATATA EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-104 DESCRIPCION DE BATATA EN EL RNCC.docx" },
    { title: "FOR-DPUV-105 DESCRIPCION DE CULTIVARES DE PITAYA EN RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-105 DESCRIPCION DE CULTIVARES DE PITAYA EN RNCC.docx" },
    { title: "FOR-DPUV-106 DESCRIPCION DE PINA EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-106 DESCRIPCION DE PINA EN EL RNCC.docx" },
    { title: "FOR-DPUV-107 DESCRIPCION DE AGUACATE COPA EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-107 DESCRIPCION DE AGUACATE COPA EN EL RNCC.docx" },
    { title: "FOR-DPUV-108 DESCRIPCION DE AGUACATE COPA EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-108 DESCRIPCION DE AGUACATE COPA EN EL RNCP.docx" },
    { title: "FOR-DPUV-109 DESCRIPCION DE AGUACATE Porta Injerto EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-109 DESCRIPCION DE AGUACATE Porta Injerto EN EL RNCP.docx" },
    { title: "FOR-DPUV-110 DESCRIPCION DE PIÑA EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/FOR-DPUV-110 DESCRIPCION DE PINA EN EL RNCP.docx" }
];

export const descripciones_departamento_proteccion = [
    { title: "DES-DPUV-100: DESCRIPCIÓN DE CULTIVARES DE SOJA EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-100%20DESCRIPCION%20DE%20SOJA%20EN%20EL%20RNCP.docx" },
    { title: "DES-DPUV-101: DESCRIPCIÓN DE CULTIVARES DE SOJA EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-101%20DESCRIPCION%20%20DE%20SOJA%20EN%20EL%20RNCC.docx" },
    { title: "DES-DPUV-102: DESCRIPCIÓN DE CULTIVARES DE TRIGO EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-102%20DESCRIPCION%20DE%20TRIGO%20EN%20EL%20RNCP.docx" },
    { title: "DES-DPUV-103: DESCRIPCIÓN DE CULTIVARES DE TRIGO EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-103%20DESCRIPCION%20DE%20TRIGO%20EN%20EL%20RNCC.docx" },
    { title: "DES-DPUV-104: DESCRIPCIÓN DE CULTIVARES DE MAIZ EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-104%20DESCRIPCION%20DE%20MAIZ%20EN%20EL%20RNCC.docx" },
    { title: "DES-DPUV-105: DESCRIPCIÓN DE CULTIVARES DE ARROZ EN El RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-105-DESCRIPCION-DE-ARROZ-EN-EL-RNCP.docx" },
    { title: "DES-DPUV-106: DESCRIPCIÓN DE CULTIVARES DE ARROZ EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-106-DESCRIPCION-DE-ARROZ-EN-EL-RNCC.docx" },
    { title: "DES-DPUV-107: DESCRIPCIÓN DE CULTIVARES DE CANOLA EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-107%20DESCRIPTOR%20DE%20CANOLA%20EN%20EL%20RNCC.doc" },
    { title: "DES-DPUV-108: DESCRIPCIÓN DE CULTIVARES DE UROCHLOA SPP. EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-108-DESCRIPCION-DE-UROCHLOA-SPP-EN-EL-RNCC.docx" },
    { title: "DES-DPUV-109: DESCRIPCIÓN DE CULTIVARES DE MIJO EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-109-DESCRIPCION-DE-MIJO-EN-EL-RNCP.docx" },
    { title: "DES-DPUV-110: DESCRIPCIÓN DE CULTIVARES DE MIJO EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-110-DESCRIPCION-DE-MIJO-EN-EL-RNCC.docx" },
    { title: "DES-DPUV-111: DESCRIPCIÓN DE CULTIVARES DE KAKI EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-111-DESCRIPCION-DE-KAKI-EN-EL-RNCC.docx" },
    { title: "DES-DPUV-112: DESCRIPCIÓN DE CULTIVARES DE SORGO EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-112-DESCRIPCION-DE-SORGO-EN-EL-RNCC.docx" },
    { title: "DES-DPUV-113: DESCRIPCIÓN DE CULTIVARES DE ACEVÉN EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-113-DESCRIPTOR-DE-ACEVEN-EN-EL-RNCC.doc" },
    { title: "DES-DPUV-114: DESCRIPCIÓN DE CULTIVARES DE JATROPHA EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-114-DESCRIPCION-DE-JATROPHA-EN-EL-RNCP.docx" },
    { title: "DES-DPUV-115: DESCRIPCIÓN DE CULTIVARES DE AVENA Spp EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-115-DESCRIPCION-DE-AVENA-EN-EL-RNCP.docx" },
    { title: "DES-DPUV-116: DESCRIPCIÓN DE CULTIVARES DE AVENA Spp EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-116-DESCRIPCION-DE-AVENA-EN-EL-RNCC.docx" },
    { title: "DES-DPUV-117: DESCRIPCIÓN DE CULTIVARES DE Urochloa spp EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-117-DESCRIPCION-DE-UROCHLOA-SPP-EN-EL-RNCP.docx" },
    { title: "DES-DPUV-118: DESCRIPCIÓN DE CULTIVARES DE PANICUM spp EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-118-DESCRIPCION-DE-MEGATHYRSUS-SPP-EN-EL-RNCP.docx" },
    { title: "DES-DPUV-119: DESCRIPCIÓN DE CULTIVARES DE Megathyrsus spp EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-119-DESCRIPCION-DE-MEGATHYRSUS-SPP-EN-EL-RNCC.docx" },
    { title: "DES-DPUV-120: DESCRIPCIÓN DE CULTIVARES DE ZARZAMORA EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-120-DESCRIPCION-DE-ZARZAMORA-EN-EL-RNCP.docx" },
    { title: "DES-DPUV-121: DESCRIPCIÓN DE CULTIVARES DE JATROPHA EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-121-DESCRIPCION-DE-JATROPHA-EN-EL-RNCC.docx" },
    { title: "DES-DPUV-122: DESCRIPCIÓN DE CULTIVARES DE AGUACATE EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-122-DESCRIPCION-DE-AGUACATE-EN-EL-RNCC.docx" },
    { title: "DES-DPUV-123: DESCRIPCIÓN DE CULTIVARES DE EUCALIPTO EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-123-DESCRIPCION-DE-EUCALIPTO-EN-EL-RNCP.docx" },
    { title: "DES-DPUV-124: DESCRIPCIÓN DE CULTIVARES DE EUCALIPTO EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-124-DESCRIPCION-DE-EUCALIPTO-EN-EL-RNCC.docx" },
    { title: "DES-DPUV-125: DESCRIPCIÓN DE CULTIVARES DE CEDRO AUSTRALIANO EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-125-DESCRIPCION-DE-CEDRO-AUSTRALIANO-EN-EL-RNCC.docx" },
    { title: "DES-DPUV-126: DESCRIPCIÓN DE CULTIVARES DE FRUTILLA EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-126-DESCRIPCION-DE-FRUTILLA-EN-EL-RNCC.docx" },
    { title: "DES-DPUV-127: DESCRIPCIÓN DE CULTIVARES DE POROTO EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-127-DESCRIPCION-DE-POROTO-EN-EL-RNCC.docx" },
    { title: "DES-DPUV-128: DESCRIPCIÓN DE CULTIVARES DE POROTO EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-128-DESCRIPCION-DE-POROTO-EN-EL-RNCP.docx" },
    { title: "DES-DPUV-129: DESCRIPCIÓN DE CULTIVARES DE CAÑA DE AZÚCAR EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-129-DESCRIPCION-DE-CANA-DE-AZUCAR-EN-EL-RNCC.docx" },
    { title: "DES-DPUV-130: DESCRIPCIÓN DE CULTIVARES DE PAPA EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-130-DESCRIPCION-DE-PAPA-EN-EL-RNCC.docx" },
    { title: "DES-DPUV-131: DESCRIPCIÓN DE CULTIVARES DE MANDIOCA EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-131-DESCRIPCION-DE-MANDIOCA-EN-EL-RNCC.docx" },
    { title: "DES-DPUV-132: DESCRIPCIÓN DE CULTIVARES DE ALGODÓN EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-132-DESCRIPCION-DE-ALGODON-EN-EL-RNCC.docx" },
    { title: "DES-DPUV-133: DESCRIPCIÓN DE CULTIVARES DE ZARZAMORA EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-133-DESCRIPCION-DE-ZARZAMORA-EN-EL-RNCC.docx" },
    { title: "DES-DPUV-134: DESCRIPCIÓN DE CULTIVARES DE MANI EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-134-DESCRIPCION-DE-MANI-EN-EL-RNCC.docx" },
    { title: "DES-DPUV-135: DESCRIPCIÓN DE CULTIVARES DE CÁÑAMO EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-135-DESCRIPCION-DE-CANAMO-EN-EL-RNCP.docx" },
    { title: "DES-DPUV-136: DESCRIPCIÓN DE CULTIVARES DE POMELO EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-136-DESCRIPCION-DE-POMELO-EN-EL-RNCC.docx" },
    { title: "DES-DPUV-137: DESCRIPTOR DE CULTIVARES DE PHOENIX DACTYLIFERA EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-137-DESCRIPTOR-DE-PHOENIX-DACTYLIFERA-EN-EL-RNCC.docx" },
    { title: "DES-DPUV-138: DESCRIPCIÓN DE CULTIVARES DE CAÑA DE AZÚCAR EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-138-DESCRIPCION-DE-CANA-DE-AZUCAR-EN-EL-RNCP.docx" },
    { title: "DES-DPUV-139: DESCRIPCIÓN DE CULTIVARES DE CÁÑAMO EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-139-DESCRIPCION-DE-CANAMO-EN-EL-RNCC.docx" },
    { title: "DES-DPUV-140: DESCRIPCIÓN DE CULTIVARES DE MANI EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-140-DESCRIPCION-DE-MANI-EN-EL-RNCP.docx" },
    { title: "DES-DPUV-141: DESCRIPCIÓN DE CULTIVARES DE CANOLA EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-141-DESCRIPCION-DE-CANOLA-EN-EL-RNCP.docx" },
    { title: "DES-DPUV-142: DESCRIPCIÓN DE CULTIVARES DE KA'A HE'E EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-142-DESCRIPCION-DE-KAA-HEE-EN-EL-RNCP.docx" },
    { title: "DES-DPUV-143: DESCRIPCIÓN DE CULTIVARES DE KA'A HE'E EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-143-DESCRIPCION-DE-KAA-HEE-EN-EL-RNCC.docx" },
    { title: "DES-DPUV-144: DESCRIPCIÓN DE CULTIVARES DE CANNABIS SP EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-144-DESCRIPCION-DE-CANNABIS-SP-EN-EL-RNCC.docx" },
    { title: "DES-DPUV-145: DESCRIPCIÓN DE CULTIVARES DE CANNABIS SP EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-145-DESCRIPCION-DE-CANNABIS-SP-EN-EL-RNCP.docx" },
    { title: "DES-DPUV-146: DESCRIPCIÓN DE CULTIVARES DE PAULOWNIA SP EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-146-DESCRIPCION-DE-PAULOWNIA-SP-EN-EL-RNCC.docx" },
    { title: "DES-DPUV-147: DESCRIPCIÓN DE CULTIVARES DE PAULOWNIA SP EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-147-DESCRIPCION-DE-PAULOWNIA-SP-EN-EL-RNCP.docx" },
    { title: "DES-DPUV-148: DESCRIPCIÓN DE CULTIVARES DE MACADAMIA SP EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-148-DESCRIPCION-DE-MACADAMIA-SP-EN-EL-RNCC.docx" },
    { title: "DES-DPUV-149: DESCRIPCIÓN DE CULTIVARES DE MACADAMIA SP EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-149-DESCRIPCION-DE-MACADAMIA-SP-EN-EL-RNCP.docx" },
    { title: "DES-DPUV-150: DESCRIPCIÓN DE CULTIVARES DE FRAMBUESO EN RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-150-DESCRIPCION-DE-FRAMBUESO-EN-EL-RNCP.docx" },
    { title: "DES-DPUV-151: DESCRIPCIÓN DE CULTIVARES DE FRAMBUESO EN RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-151-DESCRIPCION-DE-FRAMBUESO-EN-EL-RNCC.docx" },
    { title: "DES-DPUV-152: DESCRIPCIÓN DE CULTIVARES DE SÉSAMO EN RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-152-DESCRIPCION-DE-SESAMO-EN-EL-RNCC.docx" },
    { title: "DES-DPUV-153: DESCRIPCIÓN DE CULTIVARES DE SÉSAMO EN RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-153-DESCRIPCION-DE-SESAMO-EN-EL-RNCP.docx" },
    { title: "DES-DPUV-154: DESCRIPCIÓN DE CULTIVARES DE OPUNTIA EN RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-154-DESCRIPCION-DE-OPUNTIA-EN-EL-RNCP.docx" },
    { title: "DES-DPUV-155: DESCRIPCIÓN DE CULTIVARES DE FRUTILLA EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-155-DESCRIPCION-DE-FRUTILLA-EN-EL-RNCP.docx" },
    { title: "DES-DPUV-156: DESCRIPCIÓN DE CULTIVARES DE OPUNTIA EN RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-156-DESCRIPCION-DE-OPUNTIA-EN-EL-RNCC.docx" },
    { title: "DES-DPUV-157: DESCRIPCIÓN DE CULTIVARES DE BANANA EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-157-DESCRIPCION-DE-BANANA-EN-EL-RNCP.docx" },
    { title: "DES-DPUV-158: DESCRIPCIÓN DE CULTIVARES DE BANANA EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-158-DESCRIPCION-DE-BANANA-EN-EL-RNCC.docx" },
    { title: "DES-DPUV-159: DESCRIPCIÓN DE CULTIVARES DE GIRASOL EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-159-DESCRIPCION-DE-GIRASOL-EN-EL-RNCP.docx" },
    { title: "DES-DPUV-160: DESCRIPCIÓN DE CULTIVARES DE GIRASOL EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-160-DESCRIPCION-DE-GIRASOL-EN-EL-RNCC.docx" },
    { title: "DES-DPUV-161: DESCRIPCIÓN DE CULTIVARES DE TÁRTAGO (RNCP)", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-161-DESCRIPCION-DE-TARTAGO-EN-EL-RNCP.docx" },
    { title: "DES-DPUV-162: DESCRIPCIÓN DE CULTIVARES DE TÁRTAGO (RNCC)", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-162-DESCRIPCION-DE-TARTAGO-EN-EL-RNCC.docx" },
    { title: "DES-DPUV-163: DESCRIPCIÓN DE CULTIVARES DE ALGODÓN EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-163-DESCRIPCION-DE-ALGODON-EN-EL-RNCP.docx" },
    { title: "DES-DPUV-164: DESCRIPCIÓN DE CULTIVARES DE Setaria sphacelata EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-164-DESCRIPCION-DE-SETARIA-SPHACELATA-EN-EL-RNCP.docx" },
    { title: "DES-DPUV-165: DESCRIPCIÓN DE CULTIVARES DE TABACO EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-165-DESCRIPCION-DE-CULTIVARES-DE-TABACO-EN-EL-RNCP.docx" },
    { title: "DES-DPUV-166: DESCRIPCIÓN DE CEBOLLA EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-166-DESCRIPCION-DE-CEBOLLA-EN-EL-RNCP.docx" },
    { title: "DES-DPUV-167: DESCRIPCIÓN DE CEBOLLA EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-167-DESCRIPCION-DE-CEBOLLA-EN-EL-RNCC.docx" },
    { title: "DES-DPUV-168: DESCRIPCIÓN DE CULTIVARES DE TABACO EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-168-DESCRIPCION-DE-CULTIVARES-DE-TABACO-EN-EL-RNCC.docx" },
    { title: "DES-DPUV-169: DESCRIPCIÓN DE CHIA EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-169-DESCRIPCION-DE-CHIA-EN-EL-RNCC.docx" },
    { title: "DES-DPUV-170: DESCRIPCIÓN DE CHIA EN EL RNCP", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-170-DESCRIPCION-DE-CHIA-EN-EL-RNCP.docx" },
    { title: "DES-DPUV-171: DESCRIPCIÓN DE NARANJA EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-171-DESCRIPCION-DE-NARANJA-EN-EL-RNCC.docx" },
    { title: "DES-DPUV-172: DESCRIPTOR DE BRASSICA CARINATA EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-172 DESCRIPTOR DE BRASSICA CARINATA EN EL RNCC.doc" },
    { title: "DES-DPUV-173: DESCRIPCIÓN DE CULTIVARES DE TOMATE EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-173-DESCRIPCION-DE-CULTIVARES-DE-TOMATE-EN-EL-RNCC.docx" },
    { title: "DES-DPUV-174: DESCRIPCIÓN DE LOCOTE EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-174-DESCRIPCION-DE-LOCOTE-EN-EL-RNCC.docx" },
    { title: "DES-DPUV-175: DESCRIPCIÓN DE MELON EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-175 DESCRIPCION DE MELON EN EL RNCC.docx" },
    { title: "DES-DPUV-176: DESCRIPCIÓN DE BATATA EN EL RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-176-DESCRIPCION-DE-BATATA-EN-EL-RNCC.docx" },
    { title: "DES-DPUV-177: DESCRIPCIÓN DE CULTIVARES DE PITAYA EN RNCC", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DES-DPUV-177 DESCRIPCION DE CULTIVARES DE PITAYA EN RNCC.docx" }
];

// ========== NORMAS MÍNIMAS ==========

export const normasMinimas = [
    { title: "NOR-DPUV-100-NORMAS-MINIMAS-ACEVEN", url: "http://192.168.10.145/wp-content/uploads/2024/12/NOR-DPUV-100-NORMAS-MINIMAS-ACEVEN.pdf" },
    { title: "NOR-DPUV-101-NORMAS-MINIMAS-ALGODÓN", url: "http://192.168.10.145/wp-content/uploads/2024/12/NOR-DPUV-101-NORMAS-MINIMAS-ALGODÓN.pdf" },
    { title: "NOR-DPUV-102-NORMAS-MINIMAS-ARROZ", url: "http://192.168.10.145/wp-content/uploads/2024/12/NOR-DPUV-102-NORMAS-MINIMAS-ARROZ.pdf" },
    { title: "NOR-DPUV-103-NORMAS-MINIMAS-AVENA", url: "http://192.168.10.145/wp-content/uploads/2024/12/NOR-DPUV-103-NORMAS-MINIMAS-AVENA.pdf" },
    { title: "NOR-DPUV-104-NORMAS-MINIMAS-CANOLA", url: "http://192.168.10.145/wp-content/uploads/2024/12/NOR-DPUV-104-NORMAS-MINIMAS-CANOLA.pdf" },
    { title: "NOR-DPUV-105-NORMAS-MINIMAS-CAÑA-DE-AZUCAR", url: "http://192.168.10.145/wp-content/uploads/2024/12/NOR-DPUV-105-NORMAS-MINIMAS-CAÑA-DE-AZUCAR.pdf" },
    { title: "NOR-DPUV-106-NORMAS-MINIMAS-CENTENO", url: "http://192.168.10.145/wp-content/uploads/2024/12/NOR-DPUV-106-NORMAS-MINIMAS-CENTENO.pdf" },
    { title: "NOR-DPUV-107-NORMAS-MINIMAS-CROTALARIA", url: "http://192.168.10.145/wp-content/uploads/2024/12/NOR-DPUV-107-NORMAS-MINIMAS-CROTALARIA.pdf" },
    { title: "NOR-DPUV-108-NORMAS-MINIMAS-FRUTILLA", url: "http://192.168.10.145/wp-content/uploads/2024/12/NOR-DPUV-108-NORMAS-MINIMAS-FRUTILLA.pdf" },
    { title: "NOR-DPUV-109-NORMAS-MINIMAS-GIRASOL", url: "http://192.168.10.145/wp-content/uploads/2024/12/NOR-DPUV-109-NORMAS-MINIMAS-GIRASOL.pdf" },
    { title: "NOR-DPUV-110-NORMAS-MINIMAS-KAA-HEE", url: "http://192.168.10.145/wp-content/uploads/2024/12/NOR-DPUV-110-NORMAS-MINIMAS-KAA-HEE.pdf" },
    { title: "NOR-DPUV-111-NORMAS-MINIMAS-MAÍZ", url: "http://192.168.10.145/wp-content/uploads/2024/12/NOR-DPUV-111-NORMAS-MINIMAS-MAÍZ.pdf" },
    { title: "NOR-DPUV-112-NORMAS-MINIMAS-MANDIOCA", url: "http://192.168.10.145/wp-content/uploads/2024/12/NOR-DPUV-112-NORMAS-MINIMAS-MANDIOCA.pdf" },
    { title: "NOR-DPUV-113-NORMAS-MINIMAS-MANI", url: "http://192.168.10.145/wp-content/uploads/2024/12/NOR-DPUV-113-NORMAS-MINIMAS-MANI.pdf" },
    { title: "NOR-DPUV-114-NORMAS-MINIMAS-MEGATHYRSUS", url: "http://192.168.10.145/wp-content/uploads/2024/12/NOR-DPUV-114-NORMAS-MINIMAS-MEGATHYRSUS.pdf" },
    { title: "NOR-DPUV-115-NORMAS-MINIMAS-MELON", url: "http://192.168.10.145/wp-content/uploads/2024/12/NOR-DPUV-115-NORMAS-MINIMAS-MELON.pdf" },
    { title: "NOR-DPUV-116-NORMAS-MINIMAS-MIJO", url: "http://192.168.10.145/wp-content/uploads/2024/12/NOR-DPUV-116-NORMAS-MINIMAS-MIJO.pdf" },
    { title: "NOR-DPUV-117-NORMAS-MINIMAS-MOSTAZA-ETÍOPE", url: "http://192.168.10.145/wp-content/uploads/2024/12/NOR-DPUV-117-NORMAS-MINIMAS-MOSTAZA-ETÍOPE.pdf" },
    { title: "NOR-DPUV-118-NORMAS-MINIMAS-PAPA", url: "http://192.168.10.145/wp-content/uploads/2024/12/NOR-DPUV-118-NORMAS-MINIMAS-PAPA.pdf" },
    { title: "NOR-DPUV-119-NORMAS-MINIMAS-POROTO", url: "http://192.168.10.145/wp-content/uploads/2024/12/NOR-DPUV-119-NORMAS-MINIMAS-POROTO.pdf" },
    { title: "NOR-DPUV-120-NORMAS-MINIMAS-SESAMO", url: "http://192.168.10.145/wp-content/uploads/2024/12/NOR-DPUV-120-NORMAS-MINIMAS-SESAMO.pdf" },
    { title: "NOR-DPUV-121-NORMAS-MINIMAS-SOJA", url: "http://192.168.10.145/wp-content/uploads/2024/12/NOR-DPUV-121-NORMAS-MINIMAS-SOJA.pdf" },
    { title: "NOR-DPUV-122-NORMAS-MINIMAS-SORGO", url: "http://192.168.10.145/wp-content/uploads/2024/12/NOR-DPUV-122-NORMAS-MINIMAS-SORGO.pdf" },
    { title: "NOR-DPUV-123-NORMAS-MINIMAS-TABACO", url: "http://192.168.10.145/wp-content/uploads/2024/12/NOR-DPUV-123-NORMAS-MINIMAS-TABACO.pdf" },
    { title: "NOR-DPUV-124-NORMAS-MINIMAS-TOMATE", url: "http://192.168.10.145/wp-content/uploads/2024/12/NOR-DPUV-124-NORMAS-MINIMAS-TOMATE.pdf" },
    { title: "NOR-DPUV-125-NORMAS-MINIMAS-TRIGO", url: "http://192.168.10.145/wp-content/uploads/2024/12/NOR-DPUV-125-NORMAS-MINIMAS-TRIGO.pdf" },
    { title: "NOR-DPUV-126-NORMAS-MINIMAS-UROCHLOA", url: "http://192.168.10.145/wp-content/uploads/2024/12/NOR-DPUV-126-NORMAS-MINIMAS-UROCHLOA.pdf" },
    { title: "NOR-DPUV-127-NORMAS-MINIMAS-NABO", url: "http://192.168.10.145/wp-content/uploads/2024/12/NOR-DPUV-127-NORMAS-MINIMAS-NABO.pdf" },
    { title: "NOR-DPUV-128-NORMAS-MINIMAS-CENTENO", url: "http://192.168.10.145/wp-content/uploads/2024/12/NOR-DPUV-128-NORMAS-MINIMAS-CENTENO.pdf" },
    { title: "NOR-DPUV-129-NORMAS-MINIMAS-ARVEJA", url: "http://192.168.10.145/wp-content/uploads/2024/12/NOR-DPUV-129-NORMAS-MINIMAS-ARVEJA.pdf" }
];

// ========== LISTA DE TESTIGOS ==========

export const listasTestigos = [
    { title: "Testigos de variedades e híbridos de MAIZ campaña 2025/2026", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/LISTA OFICIAL DE TESTIGOS DE VARIEDADES E HIBRIDOS DE MAIZ CAMPANA 2025-2026.pdf" },
    { title: "Lista de testigos de Soja", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/DISE 1348-25 LISTA OFICIAL DE TESTIGOS VARIEDADES SOJA CAMPANA 2025-2026.pdf" },
    { title: "LISTA OFICIAL DE TESTIGOS GIRASOL 2025-2026", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/LISTA OFICIAL DE TESTIGOS GIRASOL 2025-2026.pdf" },
    { title: "LISTA OFICIAL DE TESTIGOS DE VARIEDADES DE TRIGO 2025", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/LISTA OFICIAL DE TESTIGOS DE VARIEDADES DE TRIGO PARA ENSAYOS DE EVALUACION AGRONOMICA Y DE CALIDAD 2025.pdf" },
    { title: "Lista de testigos de soja campaña 2024-2025", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/Lista%20de%20testigos%20de%20soja%20campana%202024-2025.pdf" },
    { title: "LISTA DE TESTIGOS DE VARIEDADES E HIBRIDOS DE MAIZ campaña 2024-2025", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/LISTA%20%20DE%20TESTIGOS%20DE%20VARIEDADES%20E%20HIBRIDOS%20DE%20MAIZ%20campana%202024-2025.pdf" },
    { title: "LISTA OFICIAL PARA TESTIGOS DE TRIGO CAMPAÑA 2024", url: "https://www.senave.gov.py/docs/semillas/proteccionyusovariedades/LISTA-OFICIAL-PARA-TESTIGOS-DE-TRIGO-CAMPANA-2024.pdf" }
];

// ========== DESCRIPTORES VARIETALES ==========

export const descriptoresVarietales = [
    { title: "DESCRIPCIÓN VARIETAL - ALGODÓN", url: "https://www.senave.gov.py/docs/semillas/descriptores-varietales/DESCRIPCION%20VARIETAL%20-%20ALGODON.xlsx" },
    { title: "DESCRIPCIÓN VARIETAL - ARROZ", url: "https://www.senave.gov.py/docs/semillas/descriptores-varietales/DESCRIPCION%20VARIETAL%20-%20ARROZ.xlsx" },
    { title: "DESCRIPCIÓN VARIETAL - SÉSAMO", url: "https://www.senave.gov.py/docs/semillas/descriptores-varietales/DESCRIPCION%20VARIETAL%20-%20SESAMO.xlsx" },
    { title: "DESCRIPCIÓN VARIETAL - TRIGO", url: "https://www.senave.gov.py/docs/semillas/descriptores-varietales/DESCRIPCION%20VARIETAL%20-%20TRIGO.xlsx" },
    { title: "DESCRIPCIÓN VARIETAL - MAÍZ", url: "https://www.senave.gov.py/docs/semillas/descriptores-varietales/Descripcion%20Varietal%20Maiz.xlsx" },
    { title: "DESCRIPCIÓN VARIETAL - SOJA", url: "https://www.senave.gov.py/docs/semillas/descriptores-varietales/DESCRIPCION%20VARIETAL%20-%20SOJA.xlsx" }
];

// ========== DEPARTAMENTO DE CERTIFICACIÓN DE SEMILLAS (DCS) ==========

export const procedimientosDcs = [
    { title: "PRO-DCS-001 INSCRIPCIÓN Y MANTENIMIENTO EN EL RNPS", url: "https://www.senave.gov.py/docs/semillas/procedimientos/PRO-DCS-001. INSCRIPCION Y MANTENIMIENTO EN EL RNPS..pdf" },
    { title: "PRO-DCS-002 MODIFICACIÓN DE DATOS EN EL RNPS", url: "https://www.senave.gov.py/documentos/sistema-gestion-calidad/procedimientos/7c120041027259a1e93628edfb514686.pdf" },
    { title: "PRO-DCS-003 CERTIFICACIÓN DE LA PRODUCCIÓN DE SEMILLAS", url: "https://www.senave.gov.py/documentos/sistema-gestion-calidad/procedimientos/1e7bfb63c6f59b92b83fa420488ccb19.pdf" },
    { title: "PRO-DCS-005 CERTIFICACIÓN NO DEFINITIVA DE LOTES DE SEMILLAS", url: "https://www.senave.gov.py/documentos/sistema-gestion-calidad/procedimientos/6fd585c51d4193abd385db2f196718d3.pdf" },
    { title: "PRO-DCS-008 INSPECCIÓN DE PARCELAS DE PRODUCCIÓN DE SEMILLAS", url: "https://www.senave.gov.py/documentos/sistema-gestion-calidad/procedimientos/f0cdb2c8eda9caf99a687cdca7c575bf.pdf" }
];

export const formulariosDcs = [
    { title: "FOR-DCS-002 TÉRMINO DE COMPROMISO RNPS", url: "http://192.168.10.145/wp-content/uploads/2024/12/FOR-DCS-002-TÉRMINO-DE-COMPROMISO-DEL-RESPONSABLE-TÉCNICO.doc" },
    { title: "FOR-DCS-006 SOLICITUD DE MODIFICACIÓN DE DATOS", url: "http://192.168.10.145/wp-content/uploads/2024/12/FOR-DCS-006-SOLICITUD-DE-MODIFICACIÓN-DE-DATOS-RNPS.docx" },
    { title: "FOR-DCS-013 INSPECCIÓN DE PARCELAS SEMILLERAS", url: "http://192.168.10.145/wp-content/uploads/2024/12/FOR-DCS-013-INSPECCIÓN-DE-PARCELAS-SEMILLERAS-RESPONSABLE-TÉCNICO.docx" },
    { title: "FOR-DCS-016 SOLICITUD DE EMISIÓN DE ETIQUETAS", url: "http://192.168.10.145/wp-content/uploads/2024/12/FOR-DCS-016-SOLICITUD-DE-EMISIÓN-DE-ETIQUETAS.docx" },
    { title: "FOR-DCS-018 LISTA DE LOTES CON RESULTADOS DE ANÁLISIS", url: "http://192.168.10.145/wp-content/uploads/2024/12/FOR-DCS-018-LISTA-DE-LOTES-CON-LOS-RESULTADOS-DE-ANÁLISIS-DE-CALIDAD.docx" },
    { title: "FOR-DCS-024 AUTORIZACIÓN PARA CERTIFICACIÓN NO DEFINITIVA", url: "http://192.168.10.145/wp-content/uploads/2024/12/FOR-DCS-024-AUTORIZACIÓN-PARA-LA-CERTIFICACION-NO-DEFINITIVA-DE-LOTES-DE-SEMILLAS.doc" },
    { title: "FOR-DCS-034 SOLICITUD PARA LA PRODUCCIÓN - CÍTRICOS", url: "http://192.168.10.145/wp-content/uploads/2024/12/FOR-DCS-034-SOLICITUD-DE-PLAN-DE-PRODUCCIÓN-DE-CITRICOS.doc" },
    { title: "FOR-DCS-035 INFORME DE DISPONIBILIDAD - CÍTRICOS", url: "http://192.168.10.145/wp-content/uploads/2024/12/FOR-DCS-035-INFORME-DE-DISPONIBILIDAD-DE-CÍTRICOS.docx" },
    { title: "FOR-DCS-038 SOLICITUD DE EMISIÓN DE ETIQUETAS DE CÍTRICOS", url: "http://192.168.10.145/wp-content/uploads/2024/12/FOR-DCS-038-SOLICITUD-DE-EMISIÓN-DE-ETIQUETAS-DE-CÍTRICOS.docx" },
    { title: "FORM-CERTIF-74 SOLICITUD DE REGISTRO PARA PLANTAS PROCESADORAS", url: "http://192.168.10.145/wp-content/uploads/2024/12/74-FOR-CERTIF-74-SOLICITUD-DE-REGISTRO-PARA-PLANTAS-PROCESADORAS-DE-SEMILLAS.doc" },
    { title: "FORM-CERTIF-80 SOLICITUD DE MODIFICACIÓN EN RPPS", url: "http://192.168.10.145/wp-content/uploads/2024/12/80-FOR-CERTIF-80-SOLICITUD-DE-MODIFICACIÓN-DE-DATOS-EN-EL-REGISTRO-DE-PLANTAS-PROCESADORAS-DE-SEMILLAS.doc" }
];

// ========== DEPARTAMENTO DE COMERCIO DE SEMILLAS (DCOS) ==========

export const procedimientos_dcos = [
    { title: "PRO-DCOS-200 PROCEDIMIENTO PARA LA INSCRIPCIÓN EN EL RNCS", url: "https://www.senave.gov.py/docs/semillas/comercio/PRO-DCOS-200.pdf" },
    { title: "PRO-DCOS-201 HABILITACIÓN DE SUCURSALES EN EL RNCS", url: "https://www.senave.gov.py/docs/semillas/comercio/PRO-DCOS-201%20HABILITACION%20DE%20SUCURSALES%20EN%20EL%20RNCS.pdf" },
    { title: "PRO-DCOS-202 REGISTRO NACIONAL DE COMERCIANTES DE SEMILLAS TES", url: "https://www.senave.gov.py/docs/semillas/comercio/PRO-DCOS-202%20REGISTRO%20NACIONAL%20DE%20COMERCIANTES%20DE%20SEMILLAS%20TES.pdf" }
];

export const formularios_dcos = [
    { title: "FOR-DCOS-200 SOLICITUD DE INSCRIPCIÓN RNCS", url: "https://www.senave.gov.py/docs/semillas/comercio/FOR-DCOS-200%20SOLICITUD%20DE%20INSCRIPCION%20RNCS.doc" },
    { title: "FOR-DCOS-201 TÉRMINO DE COMPROMISO RNCS", url: "https://www.senave.gov.py/docs/semillas/comercio/FOR-DCOS-201%20TERMINOS%20DE%20COMPROMISO.doc" },
    { title: "FOR-DCOS-202 DESCRIPCION DE INFRAESTRUCTURA EN EL RNCS", url: "https://www.senave.gov.py/wp-content/uploads/2024/12/FOR-DCOS-202-DESCRIPCION-DE-LA-INFRAESTRUCTURA-PARA-EL-ALMACENAMIENTO-Y-ACONDICIONAMIENTO-DE-SEMILLAS-EN-EL-RNCS.doc" },
    { title: "FOR-DCOS-203 DESCRIPCION DE INFRAESTRUCTURA DE VIVEROS EN EL RNCS", url: "https://www.senave.gov.py/wp-content/uploads/2024/12/FOR-DCOS-203-DESCRIPCION-DE-LA-INFRAESTRUCTURA-DE-VIVEROS-EN-EL-RNCS.docx" },
    { title: "FOR-DCOS-209 SOLICITUD DE MANTENIMIENTO ANUAL EN EL RNCS", url: "https://www.senave.gov.py/wp-content/uploads/2025/01/FOR-DCOS-209-SOLICITUD-DE-MANTENIMIENTO-ANUAL-EN-EL-RNCS.doc" },
    { title: "FOR-DCOS-210 TERMINO DE COMPROMISO MANTENIMIENTO RNCS", url: "https://www.senave.gov.py/wp-content/uploads/2025/01/FOR-DCOS-210-TERMINO-DE-COMPROMISO-MANTENIMIENTO-RNCS.doc" }
];
